apiVersion: v1
kind: Service
metadata:
  name: szirine-api-svc
  namespace: sz-dev-ns
  labels:
    app: szirine-api
spec:
  type: NodePort
  ports:
  - name: main
    protocol: TCP
    port: 3000
    targetPort: 3000
    #nodePort: 32000
  selector: 
    app: szirine-api
