apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: szirine-api-hpa
  namespace: sz-dev-ns
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: szirine-api-deployment
  targetCPUUtilizationPercentage: 80
